version: '2'

services:
  web:
    build: ./mynewproject
    command: python ./manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres@db/postgres

  db:
    image: postgres:9.4

